#!/usr/bin/python3
from __future__ import division, print_function
from jinja2 import Environment, FileSystemLoader
import yaml
import textwrap
import os, sys, shutil, subprocess


def file_for_zone(zone):
    return '/var/bind/rfc2136-dns-container/{zone}'.format(zone=zone)


def config_named():
    # generate rndc.key
    subprocess.run(["/usr/sbin/rndc-confgen", "-u", "named", "-a"])

    context = {
        'keys': config['keys'],
        'zones': config['zones'],
        'zone_files': { zone: file_for_zone(zone) for zone in config['zones']},
    }
    env.get_template('named.conf.j2').stream(context).dump('/etc/bind/named.conf')


def init_zones():
    if not os.path.exists('/var/bind/rfc2136-dns-container'):
        os.mkdir('/var/bind/rfc2136-dns-container')
    shutil.chown('/var/bind/rfc2136-dns-container', 'named')

    for zone in config['zones']:
        zone_file = file_for_zone(zone)
        if not os.path.exists(zone_file):
           context = { 'zone': zone }
           env.get_template('rfc2136-dns-container-initial-zone.j2').stream(context).dump(zone_file)
        shutil.chown(zone_file, 'named')


def run_cmd():
    os.execv(sys.argv[1], sys.argv[1:])


with open('/etc/bind/rfc2136-dns-container.yml', 'r') as f:
    config = yaml.safe_load(f)
env = Environment(loader=FileSystemLoader('/etc/bind'))
config_named()
init_zones()
run_cmd()

# vim:tw=120:ts=4:sw=4:expandtab:
